import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/chatone">ChatOne</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/chattwo">ChatTwo</Link>
        </li>
        <li>
          <Link to="/uploadfileone">UploadfileOne</Link>
        </li>
        <li>
          <Link to="/uploadfiletwo">UploadfileTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
